# Site settings
title: Gus' exobrain
email: gus@inodes.org
description: "Just like a real blog, only poorly written and rarely updated!"
baseurl: ""
#url: ...
#twitter_username: jekyllrb
github_username:  anguslees

# github forces these
safe: true
lsi: false
#source: .

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
sass:
  style: compressed
permalink: pretty

exclude: ["LICENSE", "README.md", "CNAME"]
